# -*- coding: utf-8 -*-
"""Clase 4 - Navegacion.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1agtW8dIBFQ_a4riHCbWWU0rPq09lK3n5
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import random
import time

# Parámetros del ambiente conocidos por el agente

# Espacio de Estados
# En este caso, está basado en las dimensiones del grid
Nfilas = 3
Ncolumnas = 4
Estados = [(x0,x1) for x0 in range(Ncolumnas) for x1 in range(Nfilas)]

# Espacio de Acciones
Acciones = ['N','S','O','E']

# Definiciones auxiliares sobre las acciones -> no todas son válidas en todos los estados
# Podríamos definir Acciones[estado], pero acá usamos la función AccionValida para verificar si una acción puede ser usada en un determinado estado.
Accion_Movimiento = {aname: np.array(a,dtype=int) for (aname,a) in zip(Acciones,[(0,1),(0,-1),(-1,0),(1,0)])}

def AccionValida(x,a):
  xp = np.array(x,dtype = int)+Accion_Movimiento[a]
  return (np.all(xp<np.array([Ncolumnas,Nfilas]))&np.all(xp>=0)) # xp está en el grid

def NombreAccion(Politica):
  return np.array(Acciones)[np.argmax(Politica, axis = 1)]

# Algunas definiciones útiles: listado de pares de estados y acciones, listado de "calles" (definidas como los segmentos de calles entre cada dos esquinas)
EstadosAcciones = [(x0,x1,a) for x0 in range(Ncolumnas) for x1 in range(Nfilas) for a in Acciones]
Calles = [(x0,x1,x0,x1+1) for x0 in range(Ncolumnas) for x1 in range(Nfilas-1)]+[(x0,x1,x0+1,x1) for x0 in range(Ncolumnas-1) for x1 in range(Nfilas)]

print('Estados = {}'.format(Estados))
print('Acciones = {}'.format(Acciones))

for x in Estados:
  for a in Acciones:
    if AccionValida(x,a):
      print(x,a,'->',tuple((np.array(x,dtype = int)+Accion_Movimiento[a]).tolist()))
    else:
      print(x,a,'Invalid')

# Vamos a almacenar matrices y vectores usando pandas dataframes. Eso es simplemente para facilitar la visualización, se puede trabajar con numpy.
# La función Indice crea un objecto multiindex para indexar nuestros dataframes y Tabla crea el dataframe con el índice y columnas necesarios.
IndiceEstados = [('x',0),('x',1)]
IndiceEstadosAcciones = [('x',0),('x',1),('a','')]
IndiceCalles = [('x',0),('x',1),('y',0),('y',1)]

def Indice(Indice, ValoresIndice):
  return pd.MultiIndex.from_tuples(ValoresIndice, names=Indice)
def Tabla(Indice, Columnas=[]):
  return pd.DataFrame(index=Indice, columns = Columnas)

# Almacenamos la función valor y la función política en una tabla que denominamos "Agente"
class Agente(pd.DataFrame):
  def __init__(self):
    Columnas = pd.MultiIndex.from_tuples([('V','')]+[('U', a) for a in Acciones])
    agente_df = Tabla(Indice(IndiceEstados, Estados), Columnas)
    agente_df['V'] = 0
    super().__init__(agente_df)

Pablo = Agente()
Pablo

# Comportamiento del Ambiente

# Los tiempos para percorrer cada segmento de calle están modelados como uniformes. Cada tramo tiene un valor promedio y un rango.
# Estos valores pueden ser conocidos o desconocidos al agente.
class Tiempos(pd.DataFrame):
  def __init__(self, TiempoEsperado, Rango):
    Rango = np.minimum(Rango, TiempoEsperado-1)
    Tiempo_df = Tabla(Indice(IndiceCalles, Calles), ['Esperado', 'Rango'])
    Tiempo_df['Rango'] = Rango
    Tiempo_df['Esperado'] = TiempoEsperado
    super().__init__(Tiempo_df)

# La clase Mapa contiene parámetros y funciones que definen el comportamiento del ambiente.
# Tenemos tres funciones esenciales y parámetros y funciones auxiliares que las acompañan:
  # Función esencial: Para todos los estados, calcula Vp(x) = min_a{ r_a(x)+E_y[V(y)|x,a]}
  # o Vp(x) = r_u(x)+E_y[V(y)|x,u(x)] si la politica u es especificada.
  # IteraciondeValor(self,V, Politica = None) -> Vp(x)

  # Función esencial: calcula la política codiciosa con respecto a la función valor V, dada por u(x) = arg min_a{ r_a(x)+E_y[V(y)|x,a]}
  # PoliticaCodiciosa(self, V) -> U

  # Función esencial: genera una muestra de recompensa r y próximo estado xp a partir de estado x in acción a.
  # Transicion_TiempoReal(self, x,a) -> (r, xp)
  # Transicion_TiempoReal es la única función que el agente puede utilizar en la situación de aprendizaje por refuerzo.
  # Las otras funciones presuponen conocimiento de las recompensas esperadas y matriz de transición.

class Mapa(object):
  def __init__(self, Tiempo, Penalidad = 500):
    self._Tiempo = Tiempo.copy()
    self._Penalidad = Penalidad*max(self._Tiempo['Esperado']+self._Tiempo['Rango'])
    self.GenerarTiempoReal()

  # Función auxiliar, se utiliza a cada día para tener una nueva muestra de los tiempos de viaje.
  def GenerarTiempoReal(self):
    # Percorrer cada calle requiere un tiempo distribuido uniformemente entre TiempoMinimo y TiempoMaximo
    self._Tiempo['Real'] = self._Tiempo['Esperado']+np.random.uniform(-self._Tiempo['Rango'],self._Tiempo['Rango']+1)

  # Función auxiliar, devuelve el tiempo esperado de viaje para cada calle.
  def TiempoEsperado(self):
    return self._Tiempo['Esperado']

  # Función auxiliar, utilizada para crear transiciones con el tiempo promedio o el tiempo real de transitar una calle.
  def _transicion(self,x,a,Tiempos):
    if ~AccionValida(x,a): # acción lleva a salir del grid
      xp = x
      r = self._Penalidad
    else:
      xp = tuple(np.array(x,dtype = int)+Accion_Movimiento[a])
      direccion = int(a in ['O','E']) # 0 si 'N', 'S', 1 si 'O', 'E'
      if a in ['O','S']: # oeste o norte
        calle = xp+x
      else: # este o norte
        calle = x+xp
      r = Tiempos[calle]
    return(r,xp)

  # Función auxiliar, utilizada en las funciones esenciales abajo. Devuelve el tiempo promedio y el próximo estado a partir de un estado x y acción a.
  def Transicion_TiempoEsperado(self,x,a):
    return self._transicion(x,a,self._Tiempo['Esperado'])

  # Función esencial: Para todos los estados, calcula Vp(x) = min_a{ r_a(x)+E_y[V(y)|x,a]}, o Vp(x) = r_u(x)+E_y[V(y)|x,u(x)] si la politica u es especificada.
  def IteraciondeValor(self,V, Politica = None):
    Vp = V.copy()
    for x in V.index:
      if x!=(Ncolumnas-1,Nfilas-1):
          # Cómo cambiaria esta parte si la transición de estado no fuera determinística?
          valores_acciones = np.array([r+V[xp] for (r,xp) in [self.Transicion_TiempoEsperado(x,a) for a in Acciones]])
          if Politica is None:
            Vp[x] = min(valores_acciones)
          else:
            Vp[x] = np.sum(Politica.loc[x]*valores_acciones)

    return Vp

  # Función esencial: calcula la política codiciosa con respecto a la función valor V, dada por u(x) = arg min_a{ r_a(x)+E_y[V(y)|x,a]}
  def PoliticaCodiciosa(self,V):
    U = Tabla(Indice(IndiceEstados, Estados), Acciones)
    U[['N','S','O','E']] = np.zeros((len(U),4))
    for x in V.index:
      if x!=(Ncolumnas-1,Nfilas-1):
          # Cómo cambiaria esta parte si la transición de estado no fuera determinística?
          valores_acciones = np.array([r+V.loc[xp] for (r,xp) in [self.Transicion_TiempoEsperado(x,a) for a in Acciones]])
          U.loc[x, Acciones[np.argmin(valores_acciones)]] = 1
    return U

  # Función esencial: genera una muestra de recompensa r y próximo estado xp a partir de estado x in acción a.
  def Transicion_TiempoReal(self,x,a):
    return self._transicion(x,a,self._Tiempo['Real'])

"""**Iteración de Valor-------------------------------------------------------**"""

# Calcular la función valor V_u de la política u, o la función valor óptima V^* si politica = None
def IteraciondeValor(Ambiente, Politica = None, epsilon = 1e-6):
  Pablo = Agente()
  Pablo.V = 0
  Vn = pd.DataFrame(Pablo.V)
  Vn.columns = [0]
  n = 0
  while True:
    # iteramos la función valor
    Vp = Ambiente.IteraciondeValor(Pablo.V, Politica)
    # Testamos si V ha convergido (diferencia entre V y Vp suficientemente pequeña)
    if np.max(np.abs(Vp-Pablo.V))<epsilon:
      break
    else:
      Pablo.V = Vp
      n = n+1
      Vn[n] = Vp

  # Especificamos la política que corresponde a la función valor. Si no se especificó la política, esa será la política óptima, que es codiciosa con respecto a V^*.
  if Politica is None:
    Pablo.U = Ambiente.PoliticaCodiciosa(Pablo.V) # la politica del agente es codiciosa con respecto a la funcion valor
  else:
    Pablo.U = Politica
  return Pablo, Vn

"""**Iteración de Política -----------------------------------------------------**"""

# Definimos algunas politicas arbitrarias que podrían ser utilizadas para inicializar el algoritmo.
def PoliticaEsteNorte():
  U = Tabla(Indice(IndiceEstados, Estados), Acciones)
  U[Acciones] = 0
  for x in U.index:
    if x!=(Ncolumnas-1,Nfilas-1):
      if AccionValida(x,'E'):
        U.loc[x,'E'] = 1
      else:
        U.loc[x,'N'] = 1
  return U

def PoliticaNorteEste():
  U = Tabla(Indice(IndiceEstados, Estados), Acciones)
  U[Acciones] = 0
  for x in U.index:
    if x!=(Ncolumnas-1,Nfilas-1):
      if AccionValida(x,'N'):
        U.loc[x,'N'] = 1
      else:
        U.loc[x,'E'] = 1
  return U

def IteraciondePolitica(Ambiente, Politica0 = None, epsilon = 1e-6):
  # Usamos esa función para convertir de política estocástica a determinística.
  def NombreAccion(Politica):
    return np.array(Acciones)[np.argmax(Politica, axis = 1)]

  # Inicializamos la politica inicial = Politica0
  if Politica0 is None:
    Politica0 = PoliticaEsteNorte()
  un = Politica0

  # Vamos a guardar los resultados intermediarios de Iteración de Política en Un. Ese paso no es esencial.
  Un = Tabla(Politica0.index)
  Un[('U', 0)] = NombreAccion(un) # Guardamos acciones por sus nombres: N, S, E, O.
  Un.columns = pd.MultiIndex.from_tuples(Un.columns)

  # evaluación de la política (iteración de valor con política fija)
  Pablo, Vn = IteraciondeValor(Ambiente,un)
  Un[('V', 0)] = Pablo.V
  n = 0
  while True:
    # actualización de la política
    un = Ambiente.PoliticaCodiciosa(Pablo.V)
    # evaluación de la política
    PabloPlus, Vn = IteraciondeValor(Ambiente,un)
    if np.max(np.abs(PabloPlus.V-Pablo.V))<epsilon: # terminamos cuando la nueva politica no mejora la función valor
      break
    else:
      n = n+1
      Pablo = PabloPlus
      Un[('U', n)] = NombreAccion(un)
      Un[('V', n)] = Pablo.V
  return Pablo, Un

"""**Aplicación de algoritmos--------------------------------------------------**"""

# Parámetros
Nfilas = 5
Ncolumnas = 5
Estados = [(x0,x1) for x0 in range(Ncolumnas) for x1 in range(Nfilas)]
Acciones = ['N','S','O','E']
EstadosAcciones = [(x0,x1,a) for x0 in range(Ncolumnas) for x1 in range(Nfilas) for a in Acciones]
Calles = [(x0,x1,x0,x1+1) for x0 in range(Ncolumnas) for x1 in range(Nfilas-1)]+[(x0,x1,x0+1,x1) for x0 in range(Ncolumnas-1) for x1 in range(Nfilas)]

CallesConTiempo = Tiempos(np.random.randint(5,10,(len(Calles),)), np.random.randint(5,8,(len(Calles),)))
Ambiente = Mapa(CallesConTiempo)

CallesConTiempo

Pablo_IV, Vn = IteraciondeValor(Ambiente)
Pablo_IP, Un = IteraciondePolitica(Ambiente)

estadisticas = Tabla(None, ['n','tiempo_VI','iteraciones_VI', 'tiempo_PI', 'iteraciones_PI'])
n = 0
for Nfilas in [2,5,10,20,30,40]:
  Ncolumnas = Nfilas
  print(Nfilas)
  for m in range(1):
    Estados = [(x0,x1) for x0 in range(Ncolumnas) for x1 in range(Nfilas)]
    Acciones = ['N','S','O','E']
    EstadosAcciones = [(x0,x1,a) for x0 in range(Ncolumnas) for x1 in range(Nfilas) for a in Acciones]
    Calles = [(x0,x1,x0,x1+1) for x0 in range(Ncolumnas) for x1 in range(Nfilas-1)]+[(x0,x1,x0+1,x1) for x0 in range(Ncolumnas-1) for x1 in range(Nfilas)]
    CallesConTiempo = Tiempos(np.random.randint(5,10,(len(Calles),)), np.random.randint(5,8,(len(Calles),)))
    Ambiente = Mapa(CallesConTiempo)
    tiempo_0 = time.time()
    Pablo_IV, Vn = IteraciondeValor(Ambiente)
    tiempo_1 = time.time()
    Pablo_IP, Un = IteraciondePolitica(Ambiente)
    tiempo_2 = time.time()
    estadisticas.loc[n] = [Nfilas, tiempo_1-tiempo_0, len(Vn.columns), tiempo_2-tiempo_1, len(Un.columns)/2]
    n = n+1
  estadisticas.to_parquet('estadisticas.parquet', compression = 'zstd')

estadisticas

plt.plot(estadisticas['n'],estadisticas['tiempo_VI'],label = 'IV')
plt.plot(estadisticas['n'],estadisticas['tiempo_PI'], label = 'IP')
plt.grid(True)
plt.title('Tiempo de ejecución')
plt.legend()
plt.show()
plt.plot(estadisticas['n'],estadisticas['iteraciones_VI'],label = 'IV')
plt.plot(estadisticas['n'],estadisticas['iteraciones_PI'],label = 'IP')
plt.grid(True)
plt.title('Número de iteraciones')
plt.legend()
plt.show()
plt.show()

"""**Aprendizaje por Refuerzo -------------------------------------------------**"""

# Evaluación de política por simulación Monte Carlo

ep_index = pd.MultiIndex(levels=[[]]*2, codes=[[]]*2, names=['episodio', 'periodo'])
ep_columns = pd.MultiIndex.from_tuples([('x',0),('x',1),('a','.'),('r','.'),('x+',0),('x+',1)])

# Definimos una politica aleatoria, que toma todas las acciones válidas con la misma probabilidad.
def PoliticaAleatoria():
  U = Tabla(Indice(IndiceEstados, Estados), Acciones)
  U[['N','S','O','E']] = np.zeros((len(U),4))
  for x in U.index:
    for accion in Acciones:
      if AccionValida(x,accion):
        U.loc[x,accion] = 1
    U.loc[x] = U.loc[x]/np.sum(U.loc[x])
  return U

# Esta función genera una trayectoria a partir del estado x0, siguiendo la política especificada, hasta llegar al estado final.
# El parámetro n es el número del episodio.
def episodio(n, Ambiente, Politica = None, x0 = None):
  # si la política no está especificada, utilizamos la política aleatoria
  if Politica is None:
    Politica = PoliticaAleatoria()
  ep = Tabla(ep_index, ep_columns)
  # si el estado inicial no está especificado, utilizamos (0,0)
  if x0 is None:
    x = (0, 0)
  else:
    x = x0
  p = 0
  while not np.array_equal(x,[Ncolumnas-1,Nfilas-1]): # mientras no estamos en el estado final
    a = random.choices(Acciones, Politica.loc[x])[0] # elegir una accion entre Acciones con distribución Politica.loc[x]
    r, xp = Ambiente.Transicion_TiempoReal(x,a) # obtenemos una muestra del próximo estado xp y recompensa r dado estado actual x y acción a
    ep.loc[(n,p),:] = np.hstack([x,a,r,xp], dtype=object) # ponemos la muestra completa (estado, acción, recompensa, estado siguiente) en el episodio
    x = xp
    p = p+1
  ep['v'] = np.cumsum(ep['r'][::-1])[::-1] # calculamos el tiempo total en el episodio que llevó ir de cada posición al destino
  return ep


def MonteCarlo(Ambiente, N, Politica = None, x0 = None):

  episodios = Tabla(ep_index, ep_columns)
  Vhatn_MC = Tabla(Indice(IndiceEstados, Estados), ['count']+list(range(N+1)))
  Vhatn_MC.loc[:, :] = 0

  if Politica is None:
    Politica = PoliticaAleatoria()

  for n in range(N):
    # empezamos en un estado aleatorio; también sería posible empezar siempre en x0 = (0,0).
    if x0 is None:
      x = random.choices([(columna,fila) for fila in range(Nfilas) for columna in range(Ncolumnas)])[0]
    else:
      x = x0
    if (n%100)==0:
      print(n, end = ' ')
    # generamos los tiempos para el episodio n
    Ambiente.GenerarTiempoReal()
    episodios = pd.concat([episodios,episodio(n, Ambiente, Politica, x)])

    # estimativa de la función valor por Monte Carlo: V(x) es el tiempo promedio de ir del estado x al estado final en los episodios
    Vhat = episodios.loc[:,['x','v']].groupby(by = [('x',0),('x',1)]).mean()
    # la función valor en el estado final es 0:
    Vhat.loc[(Ncolumnas-1, Nfilas-1),'v'] = 0
    # guardamos el número de visitas a cada estado y la estimativa de la función valor:
    counts = episodios.loc[:,['x','v']].groupby(by = [('x',0),('x',1)]).count()
    Vhatn_MC[n+1] = Vhatn_MC[n]
    Vhatn_MC.loc[Vhat.index,n+1] = Vhat['v'].values
    Vhatn_MC.loc[counts.index,'count'] = counts['v'].values

  return Vhatn_MC

# Evaluación de política por simulación Monte Carlo con bootstrapping

def MC_Bootstrapping(Ambiente,  N, Politica = None, x0 = None):

  if Politica is None:
    Politica = PoliticaAleatoria()
  Vhatn_BS = Tabla(Politica.index, ['count']+list(range(N+1)))
  Vhatn_BS.loc[:,:] = 0

  for n in range(N):
    Vhatn_BS[n+1] = Vhatn_BS[n]
    # generamos los tiempos para el episodio n
    Ambiente.GenerarTiempoReal()
    # empezamos en un estado aleatorio; también sería posible empezar siempre en x0 = (0,0).
    if x0 is None:
      x = random.choices([(columna,fila) for fila in range(Nfilas) for columna in range(Ncolumnas)])[0]
    else:
      x = x0
    if (n%100)==0:
      print(n, end = ' ')
    # simulamos transiciones de estado hasta llegar al estado final
    while not np.array_equal(x,[Ncolumnas-1,Nfilas-1]):
      a = random.choices(Acciones, Politica.loc[x])[0]
      r, xp = Ambiente.Transicion_TiempoReal(x,a)
      # a cada transicion de estado, actualizamos la función valor
      Vhatn_BS.loc[x,'count'] = Vhatn_BS.loc[x,'count']+1
      Vhatn_BS.loc[x,n+1] = Vhatn_BS.loc[x,n+1]+(r+Vhatn_BS.loc[xp,n+1]-Vhatn_BS.loc[x,n+1])/Vhatn_BS.loc[x,'count']
      x = xp

  return Vhatn_BS

episodio(0, Ambiente, Pablo_IV.U)

Politica = PoliticaEsteNorte()
Pablo_Value, Vn = IteraciondeValor(Ambiente, Politica)
N = 2000
K = 5
Vhatn_MC = {}
Vhatn_BS = {}
for k in range(K):
  print(k)
  Vhatn_MC[k] = MonteCarlo(Ambiente, N, Politica)
  Vhatn_BS[k] = MC_Bootstrapping(Ambiente, N, Politica)

plt.plot(np.sum((Vhatn_BS[0].values[:,2:]-Pablo_Value.V.values[:,np.newaxis])**2, axis=0), color = 'blue', label = 'BS')
plt.plot(np.sum((Vhatn_MC[0].values[:,2:]-Pablo_Value.V.values[:,np.newaxis])**2, axis=0), color = 'orange', label = 'MC')
for k in range(1,K):
  plt.plot(np.sum((Vhatn_BS[k].values[:,2:]-Pablo_Value.V.values[:,np.newaxis])**2, axis=0), color = 'blue')
  plt.plot(np.sum((Vhatn_MC[k].values[:,2:]-Pablo_Value.V.values[:,np.newaxis])**2, axis=0), color = 'orange')
plt.grid(True)
plt.title('Convergencia de Monte Carlo con y sin bootstrapping')
plt.legend()
plt.show()

# Q-Learning

def PoliticaQ(Q):
  # Devuelve la política a que minimiza Q(x,a) para cada estado x
  return Q.loc[Q.groupby([('x',0),('x',1)], axis = 0).V.idxmin()]

def QLearning(Ambiente, epsilon, N = 1000):

  Qhat = Tabla(Indice(IndiceEstadosAcciones, EstadosAcciones), ['count','V'])
  Qhat[:] = 0
  U_aleatoria = PoliticaAleatoria() #utilizamos la política aleatoria para agregar exploración

  for n in range(N):
    print(n, end = ' ')
    # el ambiente tiene tiempos nuevos (a partir de la misma distribución a cada episodio/día)
    Ambiente.GenerarTiempoReal()
    x = (0,0) # empezamos en el estado (0,0), pero también sería posible empezar en un estado aleatorio: random.choices([(columna,fila) for fila in range(Nfilas) for columna in range(Ncolumnas)])[0]
    while not np.array_equal(x,[Ncolumnas-1,Nfilas-1]):
      # calculamos la acción que es epsilon-greedy, equilibrando exploración y explotación
      Ux = epsilon*U_aleatoria.loc[x]
      Ux[Qhat.loc[x,'V'].idxmin()] += 1-epsilon
      # la acción que se elige es aleatorizada, con más probabilidad a la acción greedy.
      a = random.choices(Acciones, Ux)[0]
      # simulamos una transición en el ambiente, recibiendo el próximo estado xp y la recompensa r
      r, xp = Ambiente.Transicion_TiempoReal(x,a)
      # xa es el par estado-acción (x,a). Actualizamos el valor de Qhat(x,a) utilizando la observación de r y xp
      xa = x+(a,)
      Qhat.loc[xa,'count'] = Qhat.loc[xa,'count']+1
      # usamos velocidad de aprendizaje = 1/Qhat.loc[xa,'count'] = 1/N_{x,a}
      Qhat.loc[xa,'V'] = Qhat.loc[xa,'V']+(r+min(Qhat.loc[xp,'V'])-Qhat.loc[xa,'V'])/Qhat.loc[xa,'count']
      x = xp
      #print(x,a, xp)
      #print(Qhat.loc[x])

  return Qhat

CallesConTiempo

PoliticaAleatoria()

Qhat = QLearning(Ambiente, 0.01, 1000)

Pablo_IV = IteraciondeValor(Ambiente)[0]

Qhat

x = (2,4)
epsilon = 0.01
Ux = epsilon*PoliticaAleatoria().loc[x]
Ux[Qhat.loc[x,'V'].idxmin()] += 1-epsilon

Qhat.loc[x]

Ux

result = PoliticaQ(Qhat)
result['IV_accion']= NombreAccion(Pablo_IV.U)
result['IV_value'] = Pablo_IV.V.values

result

plt.plot(Qhat['count'].values)
plt.grid(True)
plt.title('Número de visitas a cada estado-acción')
plt.show()

plt.plot(1/(Qhat['count'].values+1))
plt.grid(True)
plt.title('Tasa de aprendizaje en la próxima iteración en función del estado y acción')
plt.show()